import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";
import { fileURLToPath } from "url";
import tailwindcss from "@tailwindcss/vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  root: ".", // base folder
  plugins: [react(), tailwindcss()],
  server: {
    proxy: {
      "/walker": {
        target: "http://localhost:8000",
        changeOrigin: true,
      },
    },
  },
  build: {
    rollupOptions: {
      // Use a tiny no-op entry that is NOT regenerated by jac.
      // The real app bundle is built by jac-client inside .jac/client/.
      input: "vite.entry.js",
      output: {
        entryFileNames: "client.[hash].js",
        assetFileNames: "[name].[ext]",
      },
    },
    outDir: "dist",
    emptyOutDir: true,
  },
  publicDir: "static",
  resolve: {
    alias: {
      "@jac-client/utils": path.resolve(__dirname, "src/client_runtime.js"),
      "@jac-client/assets": path.resolve(__dirname, "src/assets"),
    },
  },
});

